#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
heimdall:
  image:
    # -- image repository
    repository: linuxserver/heimdall
    # -- image tag
    tag: version-2.2.2
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See more environment variables in the [heimdall documentation](https://github.com/linuxserver/docker-heimdall#parameters).
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC
    # -- Set the container user id
    PUID: "1000"
    # -- Set the container group id
    PGID: "1000"

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: traefik
      #  annotations:
      #  cert-manager.io/cluster-issuer: letsencrypt-prod
      #  hajimari.io/appName: Jellyfin
      #  hajimari.io/icon: filmstrip
      hosts:
        - host: k3sheimdall.yourlocal.domain
          paths:
            - path: /
              pathType: Prefix


  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      type: emptyDir

  #ingressroute:
  #  enabled: true
  #  hostname: k3sheimdall.yourlocal.domain
  #  path: /
  #  #certResolver: default


